### ISSUE TITLE
Issues with Validation

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/warofcurrents#30]
I'm going through fixing some issues and making sure each of our pages are valid HTML with the W3C Schools Validator, however, I'm having some problems with the coding.html page on our website. 

https://validator.w3.org/nu/?doc=http%3A%2F%2Fwarofcurrents.newtfire.org%2Fcoding.html

I fixed the issues the Validator is marking as incorrect, yet they are still showing as being invalid. They don't exist on the page in oXygen, nor do they exist on the page itself when inspecting the code. Am I overlooking something?

@ajnewton1

**Comment by dotfig** [comment]
@quantum-satire Its fixed. It appears that you had the title and another link to a CSS in there. So I deleted the title and added the CSS in the SSI. The title would be nice to have on all pages but since we had the SSI incorporated, I don't believe we are able to put different titles on each page. So right now, all pages read "War of Currents" as its title.

**Comment by helvitiis** [comment]
@ajnewton1 Alright, now I understand. Thanks! I'll keep going through each page and making sure they're valid.
