### ISSUE TITLE
Building a Corpus

### ISSUE THREAD

**Issue by ebeshero** [quantum-satire/warofcurrents#5]
@quantum-satire Here's a direct link to our meeting notes from today, with advice on how to begin building your project "corpus" (or collection of documents to study): 

https://github.com/quantum-satire/warofcurrents/blob/master/meetingNotes/notes1.md

**Comment by dotfig** [comment]
[Pitt Library](https://www.library.pitt.edu/home) is a good way to search for newspaper articles as well

**Comment by helvitiis** [comment]
@ajnewton1 @Jamielynn92 When you get a moment, try clicking the link to the meetingNotes--they've been updated with a lot of new information since our group meeting today! Over the weekend I'm going to compile a few valid documents for us to start working with as some examples so that you'll know what to look out for when you start to search as well. I'll also be compiling a list of search terms, date ranges, and types of documents to make things easier. 
One last thing: I'd like to make sure you both get some background on the history and figures we'll be working with, so please make sure to watch [this](https://www.netflix.com/title/80058485) (episode #7) if you have Netflix (this is a short, well-made documentary that won't make you fall asleep). If you don't have Netflix, please consider reading the Biography.com links I provided in the first issue on our repo. This is very important for you to understand who they are if we are going to be creating a project centered around them!

**Comment by ebeshero** [comment]
@ajnewton1 I had to smile grimly at your comment: Ally and I spent some hours in my office this afternoon searching in the Pitt Digital Library: Specifically, we discovered that the JSTOR database in Pitt's Library could be useful because it holds articles published on the AC-DC current issues from the 1880s onwards, **and** crucially because you can copy those articles into new text files in oXygen (without having to transcribe from scratch, which we want to avoid).  Like @quantum-satire said, we added a lot more to your meeting notes file about starting to build up your collection of files to work with.

**Comment by helvitiis** [comment]
@ebeshero @ajnewton1 I am still in the process of continuing to add more to the meeting notes--hopefully I can post some helpful links with clusters of documents for DC and Edison! (Will keep everyone posted when I add anything more)
